defaults:
  - surrogate: gp
  - problem: mokp
  - override hydra/job_logging: disabled
  - _self_

acquisition:
  name:
  mc_samples: 128
  batch_size_q: 2
  sequential: true

bo:
  n_initial_samples: 10
  n_iterations: 20
  num_restarts: 10
  raw_samples: 512
  rseed: 123

hydra:
  run:
    dir: .
  output_subdir: null
