defaults:
  - problem: mokp
  - override hydra/job_logging: disabled
  - _self_

objective_index: 0
delta: 1
from_pid: 1
to_pid: 3
time_limit: 100
outputflag: 0
mipgap: 0.0
optimizer: gurobi

compute_stats_upto: 100
hypervolume:
  approx: false
  eps: 0.1
  delta: 0.1
  normalize: true
  lib: pygmo

hydra:
  run:
    dir: .
  output_subdir: null
