defaults:
  - surrogate: gp
  - problem: mokp
  - scalarization: aug_cheby
  - override hydra/job_logging: disabled
  - _self_

acquisition:
  name:
  batch_size_q: 1
  num_restarts: 10
  raw_samples: 512
  mc_samples: 128
  sequential: true

n_initial_samples: 10
n_iterations: 100
rseed: 123
time_limit: 100
compute_stats_upto: 100
from_pid: 1
to_pid: 3
optimizer: gurobi

hypervolume:
  approx: false
  eps: 0.1
  delta: 0.1
  normalize: true
  lib: pygmo

hydra:
  run:
    dir: .
  output_subdir: null
