defaults:
  - algorithm: nsga2
  - problem: mokp
  - override hydra/job_logging: disabled
  - _self_

track_generations: false
from_pid: 1
to_pid: 3
optimizer: gurobi
lib: pygmo

hydra:
  run:
    dir: .
  output_subdir: null
