defaults:
  - surrogate: gp
  - problem: mokp
  - scalarization: aug_cheby
  - override hydra/job_logging: disabled
  - _self_

acquisition:
  name:
  batch_size_q: 1
  num_restarts: 10
  raw_samples: 512
  mc_samples: 128
  sequential: true

n_initial_samples: 10
n_iterations: 10000
rseed: 123
time_limit: 100
save_prefs: false
save_objs: false

hydra:
  run:
    dir: .
  output_subdir: null
