defaults:
  - problem: mokp
  - scalarization: aug_cheby
  - override hydra/job_logging: disabled
  - _self_

n_iterations: 500
rseed: 123
time_limit: 100
save_prefs: false
save_objs: false
from_pid: 1
to_pid: 3

hydra:
  run:
    dir: .
  output_subdir: null
